#server.port=8080
#spring.jmx.enabled=false
#spring.jpa.show-sql=true
#
#spring.datasource.url = jdbc:mysql://localhost:3306/shrimp?characterEncoding=utf8
#spring.datasource.username = root
#spring.datasource.password = 
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
#spring.session.jdbc.initialize-schema=always

#
#jwt.secret= tn-secret-key-jwt
#jwt.expiration=18000

#application.properties


#show sql statement
server:
  port: 8080
  

# DB
spring:
   jmx:
      enabled: false
   jpa:
      hibernate:
          ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      generate-ddl: true
      hibernate.ddl-auto: update

      show-sql: false
   # custom show
      properties:
         hibernate:
            format_sql: true
   datasource:
      url: jdbc:mysql://localhost:3306/shrimp?characterEncoding=utf8
      username: root
      password: 

    
 
# JWT
jwt:
   secret: tn-secret-key-jwt
   # 5 hour (5 * 60 * 60)
   time-expire: 18000